# Generated by Django 4.0.6 on 2022-07-22 11:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_transaction'),
    ]

    operations = [
        migrations.RenameField(
            model_name='transaction',
            old_name='created_by',
            new_name='customer',
        ),
    ]
